name: linker

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  link:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.7.0

        with:
          fail: true
          args: --exclude-path '**/css' --exclude-path '**/javascript' --exclude-path '**/typescript' --exclude-mail